# Generated by Django 4.1.7 on 2023-03-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Srv_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNS имя сервера', models.CharField(max_length=300)),
                ('ip_addr', models.GenericIPAddressField(verbose_name='IP адрес сервера')),
                ('Category', models.CharField(max_length=100, verbose_name='Назначение сервера')),
            ],
        ),
    ]
