# Generated by Django 4.1.7 on 2023-03-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='components',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameComp', models.CharField(max_length=300, verbose_name='Наименование компонента')),
                ('nameFilepath', models.CharField(max_length=500, verbose_name='Наименование файла')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostAppServer', models.CharField(max_length=300, verbose_name='Адрес СК')),
                ('HostKafka', models.CharField(max_length=300, verbose_name='Адрес кафки')),
                ('HostScheduler', models.CharField(max_length=300, verbose_name='адрес планировщика')),
                ('HostSecurityServer', models.CharField(max_length=300, verbose_name='Наименование файла')),
                ('HostPSO', models.CharField(max_length=300, verbose_name='Наименование файла')),
                ('HostMEDO', models.CharField(max_length=300, verbose_name='Наименование файла')),
                ('DataBaseType', models.CharField(max_length=300, verbose_name='Наименование файла')),
                ('DataBaseHost', models.CharField(max_length=300, verbose_name='Наименование файла')),
                ('DataBaseName', models.CharField(max_length=300, verbose_name='Наименование файла')),
                ('DBConnetionLogin', models.CharField(max_length=300, verbose_name='Наименование файла')),
                ('DBConnetionPassword', models.CharField(max_length=300, verbose_name='Наименование файла')),
            ],
        ),
        migrations.CreateModel(
            name='Srv_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Namesrv', models.CharField(max_length=300, verbose_name='DNS имя сервера')),
                ('ip_addr', models.GenericIPAddressField(verbose_name='IP адрес сервера')),
                ('Category', models.CharField(max_length=100, verbose_name='Назначение сервера')),
                ('username', models.CharField(max_length=100, verbose_name='UserName')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('components', models.CharField(max_length=1000, verbose_name='Components')),
            ],
        ),
    ]
