# Generated by Django 4.1.7 on 2023-03-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnixApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srv_map',
            name='DNS имя сервера',
        ),
        migrations.AddField(
            model_name='srv_map',
            name='Namesrv',
            field=models.CharField(default=1, max_length=300, verbose_name='DNS имя сервера'),
            preserve_default=False,
        ),
    ]
