# Generated by Django 4.1.7 on 2023-03-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnixApp', '0002_remove_srv_map_dns имя сервера_srv_map_namesrv'),
    ]

    operations = [
        migrations.AddField(
            model_name='srv_map',
            name='password',
            field=models.CharField(default=1, max_length=100, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='srv_map',
            name='username',
            field=models.CharField(default=1, max_length=100, verbose_name='UserName'),
            preserve_default=False,
        ),
    ]
