# Generated by Django 4.1.7 on 2023-03-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnixApp', '0004_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='srv_map',
            name='components',
            field=models.CharField(default=1, max_length=1000, verbose_name='Components'),
            preserve_default=False,
        ),
    ]
